# Site Settings
baseurl: ""
url: "https://marshmellowon.github.io"
google_analytics: G-4YH4X8R26D

# Blog Settings
theme_settings:
  title: marshmellog
  description: marshmello's Blog
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/profile.jpg
    username: Sangwon Lee
    description: Photograph & Programming
    experience:
      - start: 2021-05-24
        experience: 2021 대학생 금융보안캠프(금융보안원)
      - start: 2021-02-06
        experience: TAVE Management Team
      - start: 2020-12-20
        experience: TAVE Research
        site_link: https://taveresearch.github.io/
        linkName: TAVE Research
      - start: 2020-08-01
        end: 2020-11-28
        experience: TAVE 6TH
        site_link: https://blog.naver.com/t-ave
        linkName: TAVE

    skills:
      - skill: PYTHON
        value: 10 # Percent value

  # Icons
  icons:
    email: marshmello_sw@naver.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: Marshmellowon
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: s.wlli

  # Disqus
  disqus_shortname: "marshmellowon-github-io"

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-gist]
bootstrap:
  assets: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
